# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
    ]
